from setuptools import setup, find_packages

setup(
    name='niclassify',
    version='0.3.0a',
    description='Automated insect data retrieval and classification tool',
    author='Jackson Callaghan',
    author_email='jcs.callaghan@gmail.com',
    url='https://github.com/jackson-callaghan',
    packages=find_packages(),
    package_data={
        "": ["*.json", "*.ico", "*.jpg", "*.pdf", "*.R"],
    },
    install_requires=[
        "atomicwrites",
        "attrs",
        "biopython",
        "certifi",
        "chardet",
        "clldutils",
        "colorama",
        "colorlog",
        "csvw",
        "cycler",
        "docutils",
        "ete3",
        "flake8",
        "idna",
        "iniconfig",
        "isodate",
        "joblib",
        "kiwisolver",
        "lxml",
        "matplotlib",
        "mccabe",
        "newick",
        "numpy",             # Don't hard-pin here
        "packaging",
        "pandas",
        "pillow",
        "pluggy",
        "prompt-toolkit",
        "py",
        "pycodestyle",
        "pyflakes",
        "pygments",
        "pyinquirer",
        "pyparsing",
        "pyqt5",
        "pyqt5-sip",
        "pytest",
        "python-dateutil",
        "python-nexus",
        "pytz",
        "regex",
        "requests",
        "rfc3986",
        "scikit-learn",
        "scipy",
        "seaborn",
        "six",
        "tabulate",
        "termcolor",
        "threadpoolctl",
        "toml",
        "uritemplate",
        "urllib3",
        "userpaths",
        "wcwidth",
        "xlrd",
    ],
    entry_points={
        'console_scripts': [
            'niclassify = niclassify.__main__:main'
        ]
    }
)
